.PHONY: clean All

All:
	@echo "----------Building project:[ FrankCarpetCleaning - Debug ]----------"
	@cd "FrankCarpetCleaning" && "$(MAKE)" -f  "FrankCarpetCleaning.mk"
clean:
	@echo "----------Cleaning project:[ FrankCarpetCleaning - Debug ]----------"
	@cd "FrankCarpetCleaning" && "$(MAKE)" -f  "FrankCarpetCleaning.mk" clean
