.PHONY: clean All

All:
	@echo "----------Building project:[ MainFunction - Debug ]----------"
	@cd "MainFunction" && "$(MAKE)" -f  "MainFunction.mk"
clean:
	@echo "----------Cleaning project:[ MainFunction - Debug ]----------"
	@cd "MainFunction" && "$(MAKE)" -f  "MainFunction.mk" clean
